WITH ROOT_TABLE AS (
	SELECT ITEM_ID
    FROM ITEM_TREE
    WHERE PARENT_ITEM_ID IS NULL
)
SELECT I.ITEM_ID, I.ITEM_NAME
FROM ITEM_INFO AS I
JOIN ROOT_TABLE AS R
	ON I.ITEM_ID = R.ITEM_ID
ORDER BY I.ITEM_ID