WITH UNAVAILABLE_CARS AS (
	SELECT DISTINCT CAR_ID
	    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    	WHERE NOT (END_DATE < '2022-11-01' OR START_DATE > '2022-11-30')
)

SELECT C.CAR_ID, C.CAR_TYPE, FLOOR(30 * C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)) AS FEE
	FROM CAR_RENTAL_COMPANY_CAR AS C
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    	ON C.CAR_TYPE = P.CAR_TYPE AND P.DURATION_TYPE = '30일 이상'
	WHERE C.CAR_TYPE IN ('세단', 'SUV')
    	AND C.CAR_ID NOT IN (SELECT CAR_ID FROM UNAVAILABLE_CARS)
        AND (30 * C.DAILY_FEE * (1 - P.DISCOUNT_RATE / 100)) BETWEEN 500000 AND 2000000
    ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;