SELECT S.YEAR, S.MONTH, I.GENDER, COUNT(*) AS USERS
FROM USER_INFO AS I
JOIN (
	SELECT DISTINCT USER_ID, YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH
    FROM ONLINE_SALE
) AS S
ON I.USER_ID = S.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY S.YEAR, S.MONTH, I.GENDER
ORDER BY S.YEAR, S.MONTH, I.GENDER;
