WITH TARGET_USERS AS (
	SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT 
	YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH,
    COUNT(DISTINCT(S.USER_ID)) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT(S.USER_ID)) / (SELECT COUNT(*) FROM TARGET_USERS)
    , 1) AS PURCHASED_RATIO
FROM ONLINE_SALE AS S
JOIN TARGET_USERS AS T
	ON S.USER_ID = T.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;