WITH RECURSIVE PARENT AS (
	SELECT ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, PARENT.GENERATION + 1 AS GENERATION
    FROM ECOLI_DATA AS CHILD
    JOIN PARENT
    	ON PARENT.ID = CHILD.PARENT_ID
)

SELECT COUNT(*) AS COUNT, GENERATION
FROM PARENT AS P
WHERE NOT EXISTS (
    SELECT 1
    FROM ECOLI_DATA AS T
    WHERE T.PARENT_ID = P.ID
)
GROUP BY GENERATION
ORDER BY GENERATION;