WITH MAY_TOTAL_ORDER AS (
	SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
    FROM FOOD_ORDER
    WHERE YEAR(PRODUCE_DATE) = 2022 AND MONTH(PRODUCE_DATE) = 5
    GROUP BY PRODUCT_ID
)

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, (P.PRICE * O.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT AS P
JOIN MAY_TOTAL_ORDER AS O
	ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, P.PRODUCT_ID ASC