WITH TRUCK_CARS AS (
	SELECT CAR_ID, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '트럭'
), TRUCK_HISTORY_WITH_DIFF AS (
	SELECT 
    	H.HISTORY_ID, 
    	DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS DIFF, 
    	(DATEDIFF(H.END_DATE, H.START_DATE) + 1) * C.DAILY_FEE AS TOTAL_FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    JOIN TRUCK_CARS AS C
    	ON C.CAR_ID = H.CAR_ID
), TRUCK_DISCOUNT_PLAN AS (
	SELECT 
    (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '7일 이상') AS SEVEN_DAYS, 
    (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '30일 이상') AS ONE_MONTH, 
    (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭' AND DURATION_TYPE = '90일 이상') AS THREE_MONTHS
)

SELECT H.HISTORY_ID,
	CASE
		WHEN H.DIFF BETWEEN 7 AND 29 THEN FLOOR(H.TOTAL_FEE * (100 - (SELECT SEVEN_DAYS FROM TRUCK_DISCOUNT_PLAN)) / 100)
        WHEN H.DIFF BETWEEN 30 AND 89 THEN FLOOR(H.TOTAL_FEE * (100 - (SELECT ONE_MONTH FROM TRUCK_DISCOUNT_PLAN)) / 100)
        WHEN H.DIFF >= 90 THEN FLOOR(H.TOTAL_FEE * (100 - (SELECT THREE_MONTHS FROM TRUCK_DISCOUNT_PLAN)) / 100)
        ELSE H.TOTAL_FEE
	END AS FEE
FROM TRUCK_HISTORY_WITH_DIFF AS H
ORDER BY FEE DESC, H.HISTORY_ID DESC;