WITH JULY_TOTAL AS (
	SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
)

SELECT F.FLAVOR
	FROM FIRST_HALF AS F
    LEFT JOIN JULY_TOTAL AS J
    	ON F.FLAVOR = J.FLAVOR
	ORDER BY F.TOTAL_ORDER + COALESCE(J.TOTAL_ORDER, 0) DESC
    LIMIT 3;