WITH RECURSIVE HOUR_TABLE AS (
	SELECT 0 AS HOUR -- ANCHOR QUERY
    UNION ALL
    SELECT HOUR + 1 FROM HOUR_TABLE WHERE HOUR < 23 -- RECURSIVE QUERY
)

SELECT H.HOUR, COUNT(A.DATETIME) AS COUNT
FROM HOUR_TABLE AS H
LEFT JOIN ANIMAL_OUTS AS A
	ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;