WITH MEMBER_REVIEW_COUNT AS (
	SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
), MAX_COUNT AS (
	SELECT MAX(REVIEW_COUNT) AS MAX_COUNT
    FROM MEMBER_REVIEW_COUNT
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P
JOIN MEMBER_REVIEW_COUNT AS C
	ON P.MEMBER_ID = C.MEMBER_ID
JOIN MAX_COUNT AS M
	ON C.REVIEW_COUNT = M.MAX_COUNT
JOIN REST_REVIEW AS R
	ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;