WITH MEMBER_REVIEW_COUNT AS (
	SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT, MAX(COUNT(*)) OVER () AS MAX_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
)

SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P 
JOIN MEMBER_REVIEW_COUNT AS C
	ON P.MEMBER_ID = C.MEMBER_ID
	AND C.REVIEW_COUNT = C.MAX_COUNT
JOIN REST_REVIEW AS R
	ON P.MEMBER_ID = R.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT;