WITH TARGET_CARS AS (
	SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
)

SELECT MONTH(H.START_DATE) AS MONTH, H.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
WHERE EXISTS (
	SELECT 1
    FROM TARGET_CARS AS T
    WHERE T.CAR_ID = H.CAR_ID
) AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH(H.START_DATE), H.CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH, H.CAR_ID DESC;