WITH TARGET_SKILLCODES AS (
	SELECT CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)

SELECT DISTINCT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS D
JOIN TARGET_SKILLCODES AS S
	ON (D.SKILL_CODE & S.CODE) = S.CODE
ORDER BY ID;