WITH LARGEST_YEARLY AS (
	SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_SIZE
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT Y.YEAR, Y.MAX_SIZE - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA AS E
JOIN LARGEST_YEARLY AS Y
	ON Y.YEAR = YEAR(E.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV