WITH LARGEST_FISH AS (
    SELECT 
        FISH_TYPE,
        MAX(LENGTH) AS MAX_LENGTH
    FROM 
        FISH_INFO
    GROUP BY 
        FISH_TYPE
),
LARGEST_FISH_WITH_ID AS (
    SELECT 
        FI.ID,
        FI.FISH_TYPE,
        FI.LENGTH
    FROM 
        FISH_INFO FI
    JOIN 
        LARGEST_FISH LF
    ON 
        FI.FISH_TYPE = LF.FISH_TYPE AND FI.LENGTH = LF.MAX_LENGTH
)
SELECT 
    LF.ID,
    FNI.FISH_NAME,
    LF.LENGTH
FROM 
    LARGEST_FISH_WITH_ID LF
JOIN 
    FISH_NAME_INFO FNI
ON 
    LF.FISH_TYPE = FNI.FISH_TYPE
ORDER BY 
    LF.ID ASC;