SELECT SUM(SCORE) AS SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_GRADE AS G
JOIN HR_EMPLOYEES AS E
	ON G.EMP_NO = E.EMP_NO
WHERE G.YEAR = 2022
GROUP BY EMP_NO
ORDER BY SCORE DESC
LIMIT 1;