WITH TARGET_BOARD AS (
	SELECT BOARD_ID, WRITER_ID, TITLE
    FROM USED_GOODS_BOARD
    WHERE CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
)

SELECT B.TITLE, B.BOARD_ID, R.REPLY_ID, R.WRITER_ID, R.CONTENTS, DATE_FORMAT(R.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_REPLY AS R
JOIN TARGET_BOARD AS B
	ON R.BOARD_ID = B.BOARD_ID
ORDER BY R.CREATED_DATE, B.TITLE