SELECT CONCAT('/home/grep/src/', B.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F
JOIN USED_GOODS_BOARD AS B
	ON F.BOARD_ID = B.BOARD_ID
WHERE B.VIEWS = (SELECT MAX(BN.VIEWS) FROM USED_GOODS_BOARD AS BN)
ORDER BY F.FILE_ID DESC;