WITH FE AS (
	SELECT SUM(CODE) AS CODE
    FROM SKILLCODES
    WHERE CATEGORY = 'Front End'
), PY AS (
	SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'Python'
), CS AS (
	SELECT CODE
    FROM SKILLCODES
    WHERE NAME = 'C#'
)

SELECT 
	CASE
    	WHEN SKILL_CODE & (SELECT CODE FROM FE) > 0 && SKILL_CODE & (SELECT CODE FROM PY) > 0 THEN 'A'
        WHEN SKILL_CODE & (SELECT CODE FROM CS) > 0 THEN 'B'
        ELSE 'C'        
    END AS GRADE,
    ID, EMAIL
FROM DEVELOPERS
WHERE
	(SKILL_CODE & (SELECT CODE FROM FE) > 0 AND SKILL_CODE & (SELECT CODE FROM PY) > 0)
    OR SKILL_CODE & (SELECT CODE FROM CS) > 0
    OR SKILL_CODE & (SELECT CODE FROM FE) > 0
ORDER BY GRADE, ID;
    